(cl:defpackage obstacle_challenge-srv
  (:use )
  (:export
   "PILLARDETECTION"
   "<PILLARDETECTION-REQUEST>"
   "PILLARDETECTION-REQUEST"
   "<PILLARDETECTION-RESPONSE>"
   "PILLARDETECTION-RESPONSE"
  ))

