// Generated by gencpp from file obstacle_challenge/PillarDetectionResponse.msg
// DO NOT EDIT!


#ifndef OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONRESPONSE_H
#define OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <obstacle_challenge/Pillar.h>

namespace obstacle_challenge
{
template <class ContainerAllocator>
struct PillarDetectionResponse_
{
  typedef PillarDetectionResponse_<ContainerAllocator> Type;

  PillarDetectionResponse_()
    : pillars()  {
    }
  PillarDetectionResponse_(const ContainerAllocator& _alloc)
    : pillars(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::obstacle_challenge::Pillar_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::obstacle_challenge::Pillar_<ContainerAllocator> >> _pillars_type;
  _pillars_type pillars;





  typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PillarDetectionResponse_

typedef ::obstacle_challenge::PillarDetectionResponse_<std::allocator<void> > PillarDetectionResponse;

typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionResponse > PillarDetectionResponsePtr;
typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionResponse const> PillarDetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator1> & lhs, const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pillars == rhs.pillars;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator1> & lhs, const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_challenge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05c01fe013cbbc393a81b8e5fc3bc0a8";
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05c01fe013cbbc39ULL;
  static const uint64_t static_value2 = 0x3a81b8e5fc3bc0a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_challenge/PillarDetectionResponse";
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"Pillar[] pillars\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: obstacle_challenge/Pillar\n"
"float32 centroid_x\n"
"float32 centroid_y\n"
"float32 distance\n"
"int8 color\n"
;
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pillars);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PillarDetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_challenge::PillarDetectionResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pillars: ";
    if (v.pillars.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.pillars.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::obstacle_challenge::Pillar_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.pillars[i]);
    }
    if (v.pillars.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONRESPONSE_H
