// Generated by gencpp from file obstacle_challenge/PillarDetectionRequest.msg
// DO NOT EDIT!


#ifndef OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONREQUEST_H
#define OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_challenge
{
template <class ContainerAllocator>
struct PillarDetectionRequest_
{
  typedef PillarDetectionRequest_<ContainerAllocator> Type;

  PillarDetectionRequest_()
    {
    }
  PillarDetectionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PillarDetectionRequest_

typedef ::obstacle_challenge::PillarDetectionRequest_<std::allocator<void> > PillarDetectionRequest;

typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionRequest > PillarDetectionRequestPtr;
typedef boost::shared_ptr< ::obstacle_challenge::PillarDetectionRequest const> PillarDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace obstacle_challenge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_challenge/PillarDetectionRequest";
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request (empty since client just requests data)\n"
;
  }

  static const char* value(const ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PillarDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::obstacle_challenge::PillarDetectionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTIONREQUEST_H
