// Generated by gencpp from file obstacle_challenge/PillarDetection.msg
// DO NOT EDIT!


#ifndef OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTION_H
#define OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTION_H

#include <ros/service_traits.h>


#include <obstacle_challenge/PillarDetectionRequest.h>
#include <obstacle_challenge/PillarDetectionResponse.h>


namespace obstacle_challenge
{

struct PillarDetection
{

typedef PillarDetectionRequest Request;
typedef PillarDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PillarDetection
} // namespace obstacle_challenge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::obstacle_challenge::PillarDetection > {
  static const char* value()
  {
    return "05c01fe013cbbc393a81b8e5fc3bc0a8";
  }

  static const char* value(const ::obstacle_challenge::PillarDetection&) { return value(); }
};

template<>
struct DataType< ::obstacle_challenge::PillarDetection > {
  static const char* value()
  {
    return "obstacle_challenge/PillarDetection";
  }

  static const char* value(const ::obstacle_challenge::PillarDetection&) { return value(); }
};


// service_traits::MD5Sum< ::obstacle_challenge::PillarDetectionRequest> should match
// service_traits::MD5Sum< ::obstacle_challenge::PillarDetection >
template<>
struct MD5Sum< ::obstacle_challenge::PillarDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::obstacle_challenge::PillarDetection >::value();
  }
  static const char* value(const ::obstacle_challenge::PillarDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::obstacle_challenge::PillarDetectionRequest> should match
// service_traits::DataType< ::obstacle_challenge::PillarDetection >
template<>
struct DataType< ::obstacle_challenge::PillarDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::obstacle_challenge::PillarDetection >::value();
  }
  static const char* value(const ::obstacle_challenge::PillarDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::obstacle_challenge::PillarDetectionResponse> should match
// service_traits::MD5Sum< ::obstacle_challenge::PillarDetection >
template<>
struct MD5Sum< ::obstacle_challenge::PillarDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::obstacle_challenge::PillarDetection >::value();
  }
  static const char* value(const ::obstacle_challenge::PillarDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::obstacle_challenge::PillarDetectionResponse> should match
// service_traits::DataType< ::obstacle_challenge::PillarDetection >
template<>
struct DataType< ::obstacle_challenge::PillarDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::obstacle_challenge::PillarDetection >::value();
  }
  static const char* value(const ::obstacle_challenge::PillarDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBSTACLE_CHALLENGE_MESSAGE_PILLARDETECTION_H
