// Generated by gencpp from file obstacle_challenge/Pillar.msg
// DO NOT EDIT!


#ifndef OBSTACLE_CHALLENGE_MESSAGE_PILLAR_H
#define OBSTACLE_CHALLENGE_MESSAGE_PILLAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_challenge
{
template <class ContainerAllocator>
struct Pillar_
{
  typedef Pillar_<ContainerAllocator> Type;

  Pillar_()
    : centroid_x(0.0)
    , centroid_y(0.0)
    , distance(0.0)
    , color(0)  {
    }
  Pillar_(const ContainerAllocator& _alloc)
    : centroid_x(0.0)
    , centroid_y(0.0)
    , distance(0.0)
    , color(0)  {
  (void)_alloc;
    }



   typedef float _centroid_x_type;
  _centroid_x_type centroid_x;

   typedef float _centroid_y_type;
  _centroid_y_type centroid_y;

   typedef float _distance_type;
  _distance_type distance;

   typedef int8_t _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::obstacle_challenge::Pillar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_challenge::Pillar_<ContainerAllocator> const> ConstPtr;

}; // struct Pillar_

typedef ::obstacle_challenge::Pillar_<std::allocator<void> > Pillar;

typedef boost::shared_ptr< ::obstacle_challenge::Pillar > PillarPtr;
typedef boost::shared_ptr< ::obstacle_challenge::Pillar const> PillarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_challenge::Pillar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_challenge::Pillar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_challenge::Pillar_<ContainerAllocator1> & lhs, const ::obstacle_challenge::Pillar_<ContainerAllocator2> & rhs)
{
  return lhs.centroid_x == rhs.centroid_x &&
    lhs.centroid_y == rhs.centroid_y &&
    lhs.distance == rhs.distance &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_challenge::Pillar_<ContainerAllocator1> & lhs, const ::obstacle_challenge::Pillar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_challenge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::Pillar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::Pillar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::Pillar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::Pillar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::Pillar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::Pillar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_challenge::Pillar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577a76ead12b846a3fe1693414bc0bdc";
  }

  static const char* value(const ::obstacle_challenge::Pillar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577a76ead12b846aULL;
  static const uint64_t static_value2 = 0x3fe1693414bc0bdcULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_challenge::Pillar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_challenge/Pillar";
  }

  static const char* value(const ::obstacle_challenge::Pillar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_challenge::Pillar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 centroid_x\n"
"float32 centroid_y\n"
"float32 distance\n"
"int8 color\n"
;
  }

  static const char* value(const ::obstacle_challenge::Pillar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_challenge::Pillar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centroid_x);
      stream.next(m.centroid_y);
      stream.next(m.distance);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pillar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_challenge::Pillar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_challenge::Pillar_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "centroid_x: ";
    Printer<float>::stream(s, indent + "  ", v.centroid_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "centroid_y: ";
    Printer<float>::stream(s, indent + "  ", v.centroid_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<int8_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_CHALLENGE_MESSAGE_PILLAR_H
