// Generated by gencpp from file obstacle_challenge/ultraInfo.msg
// DO NOT EDIT!


#ifndef OBSTACLE_CHALLENGE_MESSAGE_ULTRAINFO_H
#define OBSTACLE_CHALLENGE_MESSAGE_ULTRAINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace obstacle_challenge
{
template <class ContainerAllocator>
struct ultraInfo_
{
  typedef ultraInfo_<ContainerAllocator> Type;

  ultraInfo_()
    : nums()  {
    }
  ultraInfo_(const ContainerAllocator& _alloc)
    : nums(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _nums_type;
  _nums_type nums;





  typedef boost::shared_ptr< ::obstacle_challenge::ultraInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::obstacle_challenge::ultraInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ultraInfo_

typedef ::obstacle_challenge::ultraInfo_<std::allocator<void> > ultraInfo;

typedef boost::shared_ptr< ::obstacle_challenge::ultraInfo > ultraInfoPtr;
typedef boost::shared_ptr< ::obstacle_challenge::ultraInfo const> ultraInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::obstacle_challenge::ultraInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::obstacle_challenge::ultraInfo_<ContainerAllocator1> & lhs, const ::obstacle_challenge::ultraInfo_<ContainerAllocator2> & rhs)
{
  return lhs.nums == rhs.nums;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::obstacle_challenge::ultraInfo_<ContainerAllocator1> & lhs, const ::obstacle_challenge::ultraInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace obstacle_challenge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::obstacle_challenge::ultraInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::obstacle_challenge::ultraInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::obstacle_challenge::ultraInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a327f765b70d8bd267a8d96beb763ec";
  }

  static const char* value(const ::obstacle_challenge::ultraInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a327f765b70d8bdULL;
  static const uint64_t static_value2 = 0x267a8d96beb763ecULL;
};

template<class ContainerAllocator>
struct DataType< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle_challenge/ultraInfo";
  }

  static const char* value(const ::obstacle_challenge::ultraInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] nums \n"
;
  }

  static const char* value(const ::obstacle_challenge::ultraInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nums);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultraInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::obstacle_challenge::ultraInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::obstacle_challenge::ultraInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "nums: ";
    if (v.nums.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.nums.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.nums[i]);
    }
    if (v.nums.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSTACLE_CHALLENGE_MESSAGE_ULTRAINFO_H
